export const gamesRegistry = [
  {
    key: 'magic-cube',
    enabledField: 'game_one_enabled',
    title: '幸运魔方补给站',
    description: '累计 100 次必得幸运魔方，过程中还可领取阶段奖励。',
    status: 'available',
    path: '/games/magic-cube',
  },
  {
    key: 'golden-poker',
    enabledField: 'game_two_enabled',
    title: '额度牌局',
    description: '三张牌挑战庄家，可换一张，赢取站内余额。',
    status: 'available',
    path: '/games/golden-poker',
  },
  {
    key: 'quota-treasure',
    enabledField: 'game_three_enabled',
    title: '额度探宝',
    description: '逐层选择隐藏节点，随时带走奖励或继续冲击更高倍率。',
    status: 'available',
    path: '/games/quota-treasure',
  },
  {
    key: 'dice-21',
    enabledField: 'game_four_enabled',
    title: '骰盅21',
    description: '摇动暗盅接近 21 点，可重摇一次后与庄家比点。',
    status: 'available',
    path: '/games/dice-21',
  },
  {
    key: 'quota-niuniu',
    enabledField: 'game_five_enabled',
    title: '额度斗牛',
    description: '3/5 人桌模拟斗牛，支持庄家模式和抢庄模式。',
    status: 'available',
    path: '/games/quota-niuniu',
  },
];
